# Generated by Django 6.0.5 on 2026-07-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id_oficina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id_seguro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('porcentaje_cobertura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('MOTO', 'Motocicleta'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En ruta'), ('MANTENIMIENTO', 'En mantenimiento')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id_encomienda', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_seguimiento', models.CharField(max_length=30, unique=True)),
                ('nombre_destinatario', models.CharField(max_length=150)),
                ('cedula_destinatario', models.CharField(max_length=10)),
                ('email_destinatario', models.EmailField(max_length=254)),
                ('telefono_destinatario', models.CharField(max_length=15)),
                ('direccion_destino', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_declarado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('OFICINA_ORIGEN', 'En oficina de origen'), ('EN_TRANSITO', 'En tránsito'), ('OFICINA_DESTINO', 'En oficina de destino'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='REGISTRADA', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas', to='envios.cliente')),
                ('oficina_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas_destino', to='envios.oficina')),
                ('oficina_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas_origen', to='envios.oficina')),
                ('seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas', to='envios.seguro')),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas', to='envios.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionCorreo',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='envios.encomienda')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NOVEDAD', 'Novedad'), ('RETRASO', 'Retraso'), ('DANIO', 'Daño'), ('PERDIDA', 'Pérdida'), ('ENTREGA', 'Entrega')], max_length=20)),
                ('detalle', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='envios.encomienda')),
            ],
        ),
    ]
