# Generated by Django 6.0.5 on 2026-07-22 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('RETRASO', 'Retraso'), ('DANIO', 'Daño'), ('PERDIDA', 'Pérdida'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
